server:
    session:
        cookie:
            http-only: true
    port: 8081

spring:
    application:
        name: nicolas
    cloud:
        stream:
            kafka:
                binder:
                    brokers: 192.168.99.100
                    zk-nodes: 192.168.99.100
            bindings:
                data-source:
                    destination: inputtopic
                    content-type: application/json
                input:
                    destination: inputtopic
                    content-type: application/json
                output:
                    destination: outputtopic
                    content-type: application/json
                data-sink:
                    destination: outputtopic
                    content-type: application/json